language: generic

services:
  - docker

script:
  - docker build -t quay.io/adrianlucrececeleste/alpine-mkdocs:$TRAVIS_BRANCH -t quay.io/adrianlucrececeleste/alpine-mkdocs:latest .

deploy:
  - provider: script
    script: bash docker_push
    on:
      tags: true
      branch: master